.github/workflows/chore.yml

PRs like #1 are not properly assigned labels as the token associated with PRs from pull requests does not have sufficient permissions to label PRs (or leave PR comments).
- Change the trigger from `pull_request` to `pull_request_target` to execute the workflow with elevated permissions

ci: Fix the "chore" workflow for pull requests from forks

---

tests/column_types/test_float.py
tests/columns/test_rules.py

We don't correctly call `collect_schema()` everywhere where we should.

test: Remove warnings emitted in tests

---

.github/workflows/ci.yml

codecov apparently requires an upload token even for public repos (kinda makes sense, I guess).

ci: Add token for uploading code coverage

---

dataframely/_base_collection.py
dataframely/collection.py
tests/collection/test_sample.py

When providing overrides for column values in `Collection.sample`, it would be nice to optionally inline columns of members. What do I mean by that? Imagine that you have two members
```python
class A(dy.Schema):
x = dy.Int16(primary_key=True)
y = dy.Int16()
class B(dy.Schema):
x = dy.Int16(primary_key=True)
z = dy.Int16()
```
in a collection
```
class C(dy.Collection):
a: dy.LazyFrame[A]
b: dy.LazyFrame[B]
```
For sampling you can currently do
```python
C.sample(overrides=[{"a": {"y": 5}}, "b": {"z": 6}}])
```
However, it would be nice to "inline" the column values since it is clear what member `y` and `z` belong to, i.e. do
```python
C.sample(overrides=[{"y": 5, "z": 6}])
```
This significantly reduces the amount of typing required to use overrides.
- Introduce a new option …

feat: Allow to inline collection member columns for sampling

---

dataframely/collection.py
dataframely/functional.py
tests/test_typing.py

Providing a custom sampling type does not actually work all too well right now (or, rather, not at all) as `MutableMapping` is invariant. Afaict, there's no way around using `Mapping` here which is not quite as accurate but makes no practical difference as `dataframely` itself never mutates the sample (i.e. it only needs to be mutable from the user's perspective who knows the concrete type).

fix: Use covariant type annotation for collection sampling type

---

dataframely/functional.py

`Sequence` is more general than `list` and allows broader use.

fix: Use `Sequence` for `concat_collection_members`

---

dataframely/__init__.py
dataframely/columns/__init__.py
dataframely/columns/object.py
tests/column_types/test_object.py
tests/columns/test_sql_schema.py

Closes #11.
Add `dy.Object` column type as requested by the community.
For now, we don't implement sampling which is not straightforward for arbitrary python objects.

feat: Add `dy.Object` column type

---

dataframely/_base_collection.py
tests/collection/test_implementation.py
tests/collection/test_sample.py

This PR fixes two issues in one:
- Annotating optional collection members currently fails with the following issue:
```
TypeError: issubclass() arg 1 must be a class
```
- Even if that did not fail, inlining optional collection members for sampling would fail due to a missing flag

fix: Allow to make annotated collection members optional

---

dataframely/_rule.py
tests/schema/test_validate.py

Fixes #15 
* Added `nulls_equal=True` to polars join used to accumulate group rule evaluation results.

fix: Make group rules work on nullable grouping columns

---

dataframely/columns/enum.py
tests/column_types/test_enum.py

Fixes #17, which actually has nothing to do with parquet. The parquet connection just happened because the enum categories are always a `list` after going through parquet.
* Added `list` cast to ensure that `Enum.categories` is always stored as a list internally.
* Added a test that fails without the fix. @delsner @borchero : I wasn't 100% sure what file the test should be in. Let me know if you think it should go somewhere else.

fix: Make enums tolerate multiple sequence types

---

dataframely/columns/list.py
dataframely/columns/struct.py
dataframely/random.py
tests/columns/test_sample.py

`sample` should reflects the nullable property of listcolumns.
Add `_apply_null_mask` in ``List._sample_unchecked`.
series.scatter is not possible on a list series
```py
pl.Series(dtype=pl.List(pl.Int64)).scatter([0], None) 
```
So I used a pl.when().then() approach which ends up being much faster!
```py
import numpy as np
import polars as pl
s = pl.Series(range(10_000_000))
null_probability = 0.1
numpy_generator = np.random.default_rng()
random_values = numpy_generator.random(s.len())
%%timeit
null_mask = random_values < null_probability
s.scatter(np.where(null_mask)[0], None)
%%timeit
null_mask = pl.Series(random_values) > null_probability
pl.select(pl.when(null_mask).then(s)).to_series()
```
EDIT: add the same feature for struct

fix: Generate nulls for Nullable list/struct in `sample`

---

dataframely/mypy.py
tests/test_typing.py

We forgot to add `dy.Object` to the mypy plugin in #11.
Add `dy.Object` to mypy plugin.

fix: Add `dy.Object` to mypy plugin

---

dataframely/_base_schema.py
tests/schema/test_base.py

For schemas that define at least one rule, `Schema.__name__` is not set correctly (see CI on the first commit).
- Avoid shadowing `name` with rule names in the base schema constructor. 
- Add tests

fix: Correctly set dunder name for schemas with at least one rule

---

dataframely/_typing.py
tests/test_typing.py

Prior to this PR, one cannot use `pipe` with a function expecting a typed data frame, even if the source is a typed data frame. `mypy` complained with the following error:
```
error: Argument 1 to "pipe" of "LazyFrame" has incompatible type "Callable[[dataframely._typing.LazyFrame[Schema]], polars.lazyframe.frame.LazyFrame]"; expected "Callable[[polars.lazyframe.frame.LazyFrame], polars.lazyframe.frame.LazyFrame]"  [arg-type]
```

fix: Allow `pipe` to be used on typed data frames

---

dataframely/collection.py
tests/test_typing.py

`dy.Collection` currently allows specifying a generic parameter. The only purpose of this parameter is to provide a more concrete mapping type for the `sample` method in order to improve type annotations.
For one, this feels odd as the generic parameter influences a minor feature of the collection. It also clashes with the general programmer's notion that a collection's generic parameter influences the type of objects found in the collection.
In addition, however, this generic parameter also poses a serious problem when inheriting collections and wanting to sample both the parent and the child collection (as @MoritzPotthoffQC ran into).
For both of these reasons, I propose to get rid of the generic parameter.
- Remove the generic parameter from `dy.Collection`, falling back to users …

refactor: Remove generic parameter from collection

---

dataframely/exc.py
tests/collection/test_collection_future_annotations.py

I just ran into this and the exception message does not really help in understanding what is going on as you can't see that the type annotation it reads is a string. 
I thought it might be nice to explain a bit better.
- Add additional explanation if the type annotation is an actual string, so that the parsing does not work, with explicit reference to future annotations, which might be the cause.

fix: Improve exception message for invalid collection type annotations

---

dataframely/_base_schema.py
dataframely/_rule.py
dataframely/exc.py
tests/schema/test_rule_implementation.py
tests/schema/test_validate.py

Addresses #59.
We don't want to introduce a separate decorator as done in #60 with `dy.lazy_rule`. 
Instead this PR instead lazily evaluates (group-)rules and gets rid of the column check which requires all symbols used inside the rule expression to be defined (including the schema class itself).

refactor: Refactor (group-)rule to be lazily evaluated

---

dataframely/schema.py
tests/schema/test_sample.py

See #72. 
- Added `Schema._sampling_overrides` to allow setting custom column pre-processing expressions
- Extended sampling logic to apply those expressions where needed
- Added tests
Fixes #72

feat: Enable custom data frame pre-processing during schema sampling

---

README.md
dataframely/testing/rules.py
pixi.lock

Because of [this change](https://github.com/pola-rs/polars/pull/22928) in polars v1.31.0, dataframely is not compatible anymore. Some tests throw:
```
TypeError: Cannot pass a dictionary as a single positional argument.
If you merely want the *keys*, use:
• df.method(*your_dict.keys())
If you need the key value pairs, use one of:
• unpack as keywords:    df.method(**your_dict)
• build expressions:     df.method(expr.alias(k) for k, expr in your_dict.items())
```
Instead of `.drop(lf.collect_schema())` one must explicitly do `.drop(*lf.collect_schema().keys())` in `dataframely/testing/rules.py`

fix: Ensure compatibility with polars 1.31

---

dataframely/failure.py
tests/test_failure_info.py

The current logic doesn't correctly pop the `metadata` key from the `kwargs`.

fix: Allow to pass custom metadata to failure info parquets

---

dataframely/__init__.py

If one wants to override functions from the public API of `dy.Schema` or `dy.Collection`, the `Validation` literal type should also be exposed.
Add `Validation` to public API.

refactor: Move `Validation` to public API

---

dataframely/columns/_base.py

The current FutureWarning also triggers on primary key columns, which cannot be nullable anyway.
* Guarded the warning such that it is not emitted on primary key columns

fix: Only warn about nullability on non-primary-key columns

---

dataframely/collection.py
tests/collection/test_validate_input.py

This warning currently prevents users from easily piping dicts into `Collection.validate` that have extra members. This is often a useful shortcut that allows for elegant and practical code. Additionally, it is hard to imagine when a user would be happy about this warning. Even if it triggers, the user is getting what they ordered: a validated collection with the right members. There is no real opportunity for suprising / undesirable results here.
* Removed warning about superfluous columns

fix: Remove superfluous warning about superfluous collection members

---

dataframely/collection.py
tests/collection/test_serialization.py

Deserialization of collection schemas currently yields incorrect results whenever the collection has more than one filter.

fix: Correctly deserialize collections from schema

---

dataframely/_rule.py
dataframely/collection.py
dataframely/schema.py
tests/collection/test_filter_validate.py
tests/schema/test_filter.py
tests/schema/test_validate.py

This is easy to support and the guarantee might be helpful for some users. No performance difference can be detected in our benchmark setup.

refactor: Ensure `filter` and `validate` maintain order

---

dataframely/_base_collection.py
dataframely/collection.py
tests/collection/test_join.py

When working with collections, it is often helpful to filter all members by the common primary key or remove certain entries this way. 
- Added `join` method to `Collection` that allows to semi- or anti-join a collection onto a dataframe containing entries for the common primary key
- Added tests

feat: Add `join` for Collections

---

docs/sites/faq.rst

Related to #154 - feature request turned into a documentation request.
Adding the first FAQ!

docs: Add multiple unique keys FAQ recipe
